### ISSUE TITLE
Representing compound types in openapi and json schema

### ISSUE THREAD

**Issue by Fak3** [gs-gs/staruml-cefact#76] opened 2020-01-08 12:21 UTC
In the openapi schema the compound datatypes should be represented in the same way as described in #62 
 
If the property has a type "Measure", and there is a class "Measure" with one or more sub-properties, then this property should be represented as object with all sub-properties defined on that object.

For ex in this model: 
![Screenshot_20191225_143015](https://user-images.githubusercontent.com/991641/71444583-77795380-2723-11ea-9703-e004efa3cebd.jpeg)

The `NetWeight` property which have type `Measure` should be represented in the json schema as object with just one property named `UOM`.
exmaple payload:
```json
"NetWeight": {
   "UOM": "C65",
}
```
yaml schema:
```yaml
NetWeight:
     type: object
```
UOM in the mdj file have type `UNECERec20_Code` (enumeration). The definition of UNECERec20_Code is missing in the mdj file, so it should be represented as `string` in the schema, (and the user should be warned about this as described in  ticket #77)

```yaml
UOM:
     type: string
```

**Comment by faizanvahevaria** [comment] 2020-01-16 11:01
Hello @Fak3 
I have some query for below section

> The NetWeight property which have type Measure should be represented in the json schema as object with just one property named UOM.
> exmaple payload:
> 
> "NetWeight": {
>    "UOM": "C65",
> }
> yaml schema:
> 
> NetWeight:
>      type: object
> UOM in the mdj file have type UNECERec20_Code (enumeration). The definition of UNECERec20_Code is missing in the mdj file, so it should be represented as string in the schema, (and the user should be warned about this as described in ticket #77)
> 
> UOM:
>      type: string
> 

If we want to export Qualified Datatype of property (example

![001](https://user-images.githubusercontent.com/15009067/72518608-bcecf480-387b-11ea-894e-914885ee5e3d.png)

in 'TransportMeans' class for openapi, I suggest it should be exported as given below.

1. We should add class like

```
components:
  schemas:
    Measure:
      type: object
      properties:
        UOM:
          description: missing description
          type: string
```

2. It would be referenced like

```
TransportMeans:
      type: object
      properties:
        NetWeight:
          $ref: '#/components/schemas/Measure'
```

So, our whole component will look as below

```
components:
  schemas:
    Measure:
      type: object
      properties:
        UOM:
          description: missing description
          type: string
    TransportMeans:
      type: object
      properties:
        NetWeight:
          $ref: '#/components/schemas/Measure'
```
So finally the output on swagger will look as below....

![001](https://user-images.githubusercontent.com/15009067/72519480-700a1d80-387d-11ea-83d6-80d372502e14.png)

Is this fine?

**Comment by Fak3** [comment] 2020-01-16 11:04
Yes, this is fine

**Comment by faizanvahevaria** [comment] 2020-01-16 12:57
@Fak3 
If attribute type in string (ex : 'Measure') which is not legal attribute type, what we will do in this situation ?
Please attached screenshot
![001](https://user-images.githubusercontent.com/15009067/72526985-b4051e80-388d-11ea-80ff-a8e6baade9f2.png)

**Comment by faizanvahevaria** [comment] 2020-01-21 06:33
@Fak3 
As i read documentation, I seemed to know that when attribute type has reference of any UMLClass, reference should be wrapped into 'allOf' object. So, I made changes and

**Comment by Fak3** [comment] 2020-01-21 18:33
Yes, we should keep the description. So serialize it within the allOf:
```yaml
        Information:
          allOf:
            - description: lalala
            - $ref: '#/components/schemas/Text'
            - type: object
```

**Comment by Fak3** [comment] 2020-01-21 18:39
Actually the way you used on your screenshot also works, ie you can put it outside the allOf:
```yaml
        Information:
          description: lalala
          allOf:
            - $ref: '#/components/schemas/Text'
            - type: object
```

**Comment by faizanvahevaria** [comment] 2020-01-22 05:02
See the screenshot...
![001](https://user-images.githubusercontent.com/15009067/72866656-22206a00-3d02-11ea-9db5-147c9b555eaa.png)

Thats why i have put it into allOf.

So, let me know the final conclusion that which we should follow....
1) This ?
Information:
          description: lalala
          $ref: '#/components/schemas/Text'
          type: object

2) or This?
Information:
          description: lalala
          allOf:
            - $ref: '#/components/schemas/Text'
            - type: object

**Comment by Fak3** [comment] 2020-01-22 19:29
Yor example 1 is invalid, you should use one of my examples i gave above - they are both valid, and you can pick whatever is easiest to implement for you

**Comment by faizanvahevaria** [comment] 2020-01-23 04:56
> Yes, we should keep the description. So serialize it within the allOf:
> 
>         Information:
>           allOf:
>             - description: lalala
>             - $ref: '#/components/schemas/Text'
>             - type: object

I am following this

**Comment by Fak3** [comment] 2020-01-24 16:43
lgtm

**Comment by onthebreeze** [comment] 2020-02-11 11:06
whilst this issue and the fix is technically correct, the problem is that the rules are hard coded into the generator.  

So, if a UML attribute has a type Text then the generator will always make a compound type with language and pattern properties.  But sometimes the designer may not want that.  Maybe he wants a simple string.  maybe just language.  maybe some other property.  

I think that the generator should follow what is actually modelled.  So IF the model file has actually defined a class for TEXT type and it has some properties like langauge and pattern, then generate them.  If not then just apply simple default rules as follows:

* Text type -> JSON string
* Date or DateTime type -> json string with format qualifier - date-time or date or time as per json schema spec.

**Comment by faizanvahevaria** [comment] 2020-02-12 14:05
@Fak3
Latest code is updated please test this issue

**Comment by Fak3** [comment] 2020-02-18 19:46
> @onthebreeze wrote: So IF the model file has actually defined a class for TEXT type and it has some properties like langauge and pattern, then generate them. If not then just apply simple default rules

I will try to expand the formal behavior, please correct me If it does not make sense:

### Case 1
 If there is a class defined in the uml file, and this class has at least one property, then it should be represented as compound type. OpenAPI spec should have an object schema corresponding to this class, and properties which are declared to have a reange of this class should use a `$ref` to the schema. For example:
![Screenshot_20200218_222547](https://user-images.githubusercontent.com/991641/74770512-71c06a00-529d-11ea-9e41-a42074aef9d9.jpeg)
![Screenshot_20200218_223254](https://user-images.githubusercontent.com/991641/74770996-6faadb00-529e-11ea-97cc-57d106869042.jpeg)
Should be represented like this:
```
    Information:
      allOf:
        - description: lalala
        - $ref: '#/components/schemas/Text'
        - type: object
```

### Case2 
If there is no class defined in the uml file, OR if the class does not have any child properties defined. For ex.:
![Screenshot_20200218_223453](https://user-images.githubusercontent.com/991641/74771166-b567a380-529e-11ea-8bee-19fc1f702769.jpeg)
There are two sub-cases:
 * Case 2a) If the name of the type is one of the following, then it should be represented as described below:
```
          'Text': 'string'
          'Numeric':'number';
          'Indicator':'boolean';
          'Date':'string';
               itemsObj.format = 'date';
          'DateTime':'string';
               itemsObj.format = 'date-time';
          'Integer':'integer';
          'Int32':'integer';
               itemsObj.format = 'int32';
          'Int64':'integer';
               itemsObj.format = 'int64';
          'Number':'number';
          'Float':'number';
               itemsObj.format = 'float';
          'Double':'number';
               itemsObj.format = 'double';
          'Boolean':'boolean';
          'Password':'string';
               itemsObj.format = "password";
          'Byte':'string';
               itemsObj.format = 'byte';
          'Binary':'string';
               itemsObj.format = 'binary';
```
There should NOT be a warning in this case even if the class is completely missing from the uml file.

Case 2b) if the name of the type is NOT one of the given in the list above (2a), then it should be represented as simple 'string' in the openapi file, and there should be a warning printed to the user:
> Warning: your json schema may be invalid because following properties have unknown or undefined type:
> Measure.UOM: UNECERec20_Code
> Binary.MIMEType: MIME_Code
... (other missing types)

The file should still be generated, the warning should not prevent the user to proceed at his own risk.

**Comment by onthebreeze** [comment] 2020-02-18 20:02
Yes - well said.  

So in the case of the Text types in the import declaration model, they would come out as simple string because there is no corresponding Text class defined

**Comment by faizanvahevaria** [comment] 2020-02-21 12:10
@Fak3  @onthebreeze 
Latest code is updated to master branch so please test this issue and close if it work fine

**Comment by Fak3** [comment] 2020-02-24 10:32
@faizanvahevaria does not work properly for me. This sample [file](https://edi3.org/specs/edi3-uml-profile/develop/SampleModel.mdj) have Identifier and Code declared:
![Screenshot_20200224_133042](https://user-images.githubusercontent.com/991641/75145399-ee25d380-5709-11ea-8e7d-9ca755f701fc.jpeg)
But when i export openapi it gives me warning about Identifier and Code, while it should not:
![Screenshot_20200224_132316](https://user-images.githubusercontent.com/991641/75144960-2678e200-5709-11ea-82f9-5d88a3becd6f.jpeg)

**Comment by Fak3** [comment] 2020-02-24 10:46
What is more weird is that Code has proper schema in the output file:
```
    Code:
      type: object
      properties:
        Scheme:
          description: missing description
          type: string
      required:
        - Scheme
```
But Identifier does not. They are both belong to Case1, so this is quite surprising

**Comment by Fak3** [comment] 2020-02-24 12:10
As @faizanvahevaria pointed out at a call - this file has some properties linked to its type, like `PassengerNationality` on the screenshot:

![Screenshot_20200224_150324](https://user-images.githubusercontent.com/991641/75151145-00f2d500-5717-11ea-8bec-4db80ff96529.jpeg)

And some properties does not have a link to the type, like `Stage`:

![Screenshot_20200224_144340](https://user-images.githubusercontent.com/991641/75151205-2aabfc00-5717-11ea-882d-4f50d4a433de.jpeg)

@onthebreeze should the openapi plugin treat those two cases differently? I can't think of any example when a user intentionally wants to make properties different in this way, so am I right, that the plugin should treat both cases the same? (Perhaps warn a user if there are unlinked properties like `Stage` in the file)

**Comment by faizanvahevaria** [comment] 2020-02-26 14:09
@onthebreeze @Fak3 
please test this issue from latest code and close if it work fine

**Comment by Fak3** [comment] 2020-02-27 18:36
Looks okay, but the path where it stores the error log should be changed, i think it should be in the same dir as output schema file. Currently plugin tries to save it in the staruml config dir, which is too hard to find:

![Screenshot_20200227_213409](https://user-images.githubusercontent.com/991641/75474830-bdaf9500-59a8-11ea-8906-6d5afff25ccd.jpeg)

And then there is an error that the file location does not exist:

![Screenshot_20200227_213511](https://user-images.githubusercontent.com/991641/75474918-dcae2700-59a8-11ea-841f-8ba7726eaa6b.jpeg)

**Comment by faizanvahevaria** [comment] 2020-04-08 05:02
@Fak3 
This issue is resolved so i am going to close this ticket

**Closed by faizanvahevaria** 2020-04-08 05:02 UTC
